# Generated by Django 2.0.2 on 2018-11-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PRmanage', '0008_pianoroom_user_group'),
        ('USERmanage', '0009_auto_20181118_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(verbose_name='费用 /元')),
                ('is_pay', models.BooleanField(choices=[(True, '已缴费'), (False, '待缴费')], verbose_name='缴费情况')),
                ('user_quantity', models.IntegerField(verbose_name='人数')),
                ('star_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '已取消'), (1, '未赴约'), (2, '已赴约')], verbose_name='状态')),
                ('piano_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRmanage.PianoRoom', verbose_name='琴房')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERmanage.User', verbose_name='用户')),
            ],
        ),
    ]
