# Generated by Django 2.0.2 on 2018-11-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrecord',
            options={'verbose_name': '预约记录', 'verbose_name_plural': '预约记录'},
        ),
        migrations.RenameField(
            model_name='bookrecord',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
