# Generated by Django 2.0.2 on 2018-11-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKmanage', '0002_auto_20181118_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookrecord',
            name='start_time',
        ),
    ]
