# Generated by Django 2.0.2 on 2018-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKmanage', '0004_auto_20181130_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='BR_date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='bookrecord',
            name='use_time',
            field=models.IntegerField(choices=[(1, '8-9'), (2, '9-10'), (3, '10-11'), (4, '11-12'), (5, '12-13'), (6, '13-14'), (7, '14-15'), (8, '15-16'), (9, '16-17'), (10, '17-18'), (11, '18-19'), (12, '19-20'), (13, '20-21'), (14, '21-22')], verbose_name='时间段'),
        ),
    ]
