# Generated by Django 2.1.3 on 2018-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BOOKmanage', '0005_auto_20181130_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecord',
            name='user_quantity',
            field=models.BooleanField(choices=[(True, '单人'), (False, '多人')], verbose_name='单人/多人'),
        ),
    ]
