# Generated by Django 2.0.2 on 2018-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='组名')),
                ('xinghaiPR_price', models.IntegerField(verbose_name='星海琴房 元/时')),
                ('smallPR_price', models.IntegerField(verbose_name='小琴房 元/时')),
                ('bigPR_price', models.IntegerField(verbose_name='大琴房 元/时')),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
            },
        ),
    ]
