# Generated by Django 2.0.2 on 2018-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTroupeMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32, verbose_name='学生证号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '艺术团成员',
                'verbose_name_plural': '艺术团成员',
            },
        ),
        migrations.CreateModel(
            name='OrdinaryStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=32, verbose_name='学生证号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '普通学生',
                'verbose_name_plural': '普通学生',
            },
        ),
        migrations.CreateModel(
            name='SocialPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('person_id', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '校外人士',
                'verbose_name_plural': '校外人士',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('teacher_id', models.CharField(db_index=True, max_length=32, verbose_name='教职工号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '教职工',
                'verbose_name_plural': '教职工',
            },
        ),
    ]
