# Generated by Django 2.0.2 on 2018-11-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0002_arttroupemember_ordinarystudent_socialperson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arttroupemember',
            name='open_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='ordinarystudent',
            name='open_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='socialperson',
            name='open_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='open_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
    ]
