# Generated by Django 2.0.2 on 2018-11-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0003_auto_20181118_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('person_id', models.CharField(db_index=True, max_length=32, verbose_name='学号/教职工号/身份证')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERmanage.UserGroup')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='arttroupemember',
            options={'verbose_name': '艺术团', 'verbose_name_plural': '艺术团'},
        ),
    ]
