# Generated by Django 2.0.2 on 2018-11-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0004_auto_20181118_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdinaryStudent',
        ),
        migrations.DeleteModel(
            name='SocialPerson',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.RemoveField(
            model_name='arttroupemember',
            name='open_id',
        ),
    ]
