# Generated by Django 2.0.2 on 2018-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0006_auto_20181118_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='open_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='open_id'),
        ),
    ]
