# Generated by Django 2.0.2 on 2018-11-18 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0007_auto_20181118_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='open_id')),
                ('person_id', models.CharField(db_index=True, max_length=32, verbose_name='学号/教职工号/身份证号')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERmanage.UserGroup', verbose_name='用户组')),
            ],
            options={
                'verbose_name': '黑名单',
                'verbose_name_plural': '黑名单',
            },
        ),
    ]
