# Generated by Django 2.0.2 on 2018-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0008_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='person_id',
            field=models.CharField(db_index=True, max_length=32, verbose_name='学号/教职工号/身份证'),
        ),
    ]
