# Generated by Django 2.1.3 on 2018-12-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0009_auto_20181118_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=32, verbose_name=u'密码'),
        ),
        migrations.AlterField(
            model_name='arttroupemember',
            name='student_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name=u'学生证号'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='person_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name=u'学号/教职工号/身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='person_id',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name=u'学号/教职工号/手机号'),
        ),
    ]
