# Generated by Django 2.0.2 on 2018-11-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='close_time',
            field=models.TimeField(db_index=True, verbose_name='关闭时间'),
        ),
        migrations.AlterField(
            model_name='pianoroom',
            name='open_time',
            field=models.TimeField(db_index=True, verbose_name='开放时间'),
        ),
        migrations.AlterField(
            model_name='pianoroom',
            name='piano_type',
            field=models.CharField(max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pianoroom',
            name='room_id',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='pianoroom',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
    ]
