# Generated by Django 2.0.2 on 2018-11-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0003_auto_20181116_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='status',
            field=models.IntegerField(choices=[(-1, '停止使用'), (0, '已被预约'), (1, '可被预约')], max_length=2, verbose_name='状态'),
        ),
    ]
