# Generated by Django 2.0.2 on 2018-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0004_auto_20181116_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('published_time', models.DateTimeField()),
                ('published_person', models.CharField(max_length=12, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '琴房公告',
                'verbose_name_plural': '琴房公告',
            },
        ),
    ]
