# Generated by Django 2.0.2 on 2018-11-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0005_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='status',
            field=models.IntegerField(choices=[(-1, '停止使用'), (0, '已被预约'), (1, '可被预约')], verbose_name='状态'),
        ),
    ]
