# Generated by Django 2.0.2 on 2018-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0006_auto_20181116_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='published_time',
            field=models.DateTimeField(verbose_name='发布时间'),
        ),
    ]
