# Generated by Django 2.0.2 on 2018-11-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERmanage', '0009_auto_20181118_2109'),
        ('PRmanage', '0007_auto_20181116_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='pianoroom',
            name='user_group',
            field=models.ManyToManyField(to='USERmanage.UserGroup', verbose_name='允许用户组'),
        ),
    ]
