# Generated by Django 2.0.2 on 2018-11-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0008_pianoroom_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pianoroom',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='pianoroom',
            name='open_time',
        ),
        migrations.AlterField(
            model_name='pianoroom',
            name='status',
            field=models.IntegerField(choices=[(0, '停止使用'), (1, '开放使用')], verbose_name='状态'),
        ),
    ]
