# Generated by Django 2.0.2 on 2018-11-20 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0009_auto_20181120_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(choices=[(0, '今天'), (1, '明天'), (2, '后天')], default=0, verbose_name='日期')),
                ('open_time', models.TimeField(db_index=True, verbose_name='开放时间')),
                ('close_time', models.TimeField(db_index=True, verbose_name='关闭时间')),
                ('Time', models.DurationField(default=datetime.timedelta(0), verbose_name='1th')),
            ],
            options={
                'verbose_name': '时间表',
                'verbose_name_plural': '时间表',
            },
        ),
    ]
