# Generated by Django 2.0.2 on 2018-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0016_remove_timetable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='TT_type',
            field=models.IntegerField(choices=[(0, '今天'), (1, '明天'), (2, '后天')], default=0, verbose_name='类型'),
        ),
    ]
