# Generated by Django 2.0.2 on 2018-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0017_timetable_tt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='日期'),
        ),
    ]
