# Generated by Django 2.1.3 on 2018-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0020_auto_20181204_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='room_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='编号'),
        ),
    ]
