# Generated by Django 2.1.3 on 2018-12-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0021_auto_20181205_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='room_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='编号'),
        ),
    ]
