# Generated by Django 2.1.3 on 2018-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0024_auto_20181206_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='room_id',
            field=models.CharField(max_length=24, unique=True, verbose_name='编号'),
        ),
    ]
