# Generated by Django 2.1.3 on 2018-12-06 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0034_auto_20181206_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='piano_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='PRmanage.PianoRoom', to_field='room_id', verbose_name='琴房'),
        ),
    ]
