# Generated by Django 2.1.3 on 2018-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRmanage', '0036_auto_20181206_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoroom',
            name='room_id',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='编号'),
        ),
    ]
